# Generated by Django 2.0.2 on 2018-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyFirstModel',
            new_name='TestModel',
        ),
    ]
