# Generated by Django 2.0.2 on 2018-05-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180521_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='Question',
        ),
    ]
